package com.jiuqi.jnds05.common.dao;

public class ProjectExpenditureDetailsDao {

	public String ProjectExpenditureTop10() {
		String sql = "SELECT BB.STDNAME,AA.ZCJE FROM ( \n"
				+ "SELECT C.PROJECTID,SUM(A.DEBIT-A.CREDIT) AS ZCJE FROM GL_VOUCHERITEM A \n"
				+ "LEFT JOIN GL_VOUCHER B ON B.RECID = A.VCHRID \n"
				+ "LEFT JOIN GL_ASSISTCOMB C ON C.RECID = A.ASSCOMBID \n"
				+ "LEFT JOIN MD_ACCOUNTSUBJECT D ON D.RECID = A.SUBJECTID AND D.ACCTYEAR = 2019 \n" + "WHERE 1=1  \n"
				+ "AND B.ACCTYEAR = 2019 \n" + "AND B.UNITID = '67F3F734A00001C1B70D7708DC3B7F70' \n"
				+ "AND B.ACCTPERIOD <> 0 \n"
				+ "AND (D.STDCODE LIKE '720102%' OR D.STDCODE LIKE '730102%' OR D.STDCODE LIKE '740102%' OR D.STDCODE LIKE '750102%' OR D.STDCODE LIKE '790102%') \n"
				+ "GROUP BY C.PROJECTID \n" + ") AA \n"
				+ "LEFT JOIN MD_PROJECT BB ON BB.RECID = AA.PROJECTID AND BB.ACCTYEAR = 2019 \n"
				+ "ORDER BY AA.ZCJE DESC \n";
		return sql;
	}

}
