package com.jiuqi.dna.jnjs.service;

import java.util.LinkedHashMap;
import java.util.Map;

import com.jiuqi.dna.core.Context;
import com.jiuqi.dna.core.da.DBCommand;
import com.jiuqi.dna.core.da.RecordSet;
import com.jiuqi.dna.core.da.RecordSetField;
/**
 *固定和无形资产存量情况表
 * 1、该表期初账面数根据获取卡片表中“000223单位”
 * （单位编号为：000223）2018年12月31日前存量信息；
 * 期末数获取卡片表中“000223单位”（单位编号为：000223）
 *  2019年12月31日前存量信息。
 * 2、期初账面数取数逻辑解析（取数逻辑中单位条件固定为：“000223单位”）：
 * @param conn
 * @return
 * @author zhagnwei
 *
 */
public class  Gdzc_wxzcService{
	
	/**
	 *1、该表期初账面数根据获取卡片表中“000223单位”
     * （单位编号为：000223）2018年12月31日前存量信息；
     * 期末数获取卡片表中“000223单位”（单位编号为：000223）
	 * @param conn
	 * @param acctyear
	 * @return
	 */
	public static Map<String,Double> getGdzc_wxzc_qm(Context conn,int acctyear){
		Map<String,Double> mapSR = new LinkedHashMap<String,Double>();
		StringBuffer sb = new StringBuffer();
		sb.append("  define query getGdzc_wxzc_qc(@acctyear int) begin  ");
		sb.append("   select sum(case when cla.stdcode like '2%' then card.shul else 0 end) as g8,                                                                                                                                                                                                                                        \n");
		sb.append("          sum(case when cla.stdcode like '3%' then card.shul else 0 end) as g9,                                                                                                                                                                                                                                        \n");
		sb.append("          sum(case when cla.stdcode like '4%' then card.shul else 0 end) as g10,                                                                                                                                                                                                                                       \n");
		sb.append("          sum(case when cla.stdcode like '5%' then card.shul else 0 end) as g11,                                                                                                                                                                                                                                       \n");
		sb.append("          sum(case when cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%' then card.shul else 0 end) as g12,                                                                                                                                                     \n");
		sb.append("          sum(case when cla.stdcode like '1%'or cla.stdcode like '2%'or cla.stdcode like '3%'or cla.stdcode like '4%'or cla.stdcode like '5%' or cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%'or cla.stdcode like '604%'or cla.stdcode like '605%' then card.jiaz else 0 end) as h5,    \n");
		sb.append("          sum(case when cla.stdcode like '1%'or cla.stdcode like '2%'or cla.stdcode like '3%'or cla.stdcode like '4%'or cla.stdcode like '5%' or cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%'or cla.stdcode like '604%' then card.jiaz else 0 end) as h6,                              \n");
		sb.append("          sum(case when cla.stdcode like '101%'or cla.stdcode like '102%' or cla.stdcode like '103%' then card.jiaz else 0 end) as h7,                                                                                                                                                                                 \n");
		sb.append("          sum(case when cla.stdcode like '2%' then card.jiaz else 0 end) as h8,                                                                                                                                                                                                                                        \n");
		sb.append("          sum(case when cla.stdcode like '3%' then card.jiaz else 0 end) as h9,                                                                                                                                                                                                                                        \n");
		sb.append("          sum(case when cla.stdcode like '4%' then card.jiaz else 0 end) as h10,                                                                                                                                                                                                                                        \n");
		sb.append("          sum(case when cla.stdcode like '5%' then card.jiaz else 0 end) as h11,                                                                                                                                                                                                                                       \n");
		sb.append("          sum(case when cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%'  then card.jiaz else 0 end) as h12,                                                                                                                                                    \n");
		sb.append("          sum(case when cla.stdcode like '605%' then card.jiaz else 0 end) as h13,                                                                                                                                                                                                                                     \n");
		sb.append("          sum(case when cla.stdcode like '1%'or cla.stdcode like '2%'or cla.stdcode like '3%'or cla.stdcode like '4%'or cla.stdcode like '5%' or cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%'or cla.stdcode like '604%'or cla.stdcode like '605%' then card.leijzj else 0 end) as i5,  \n");
		sb.append("          sum(case when cla.stdcode like '1%'or cla.stdcode like '2%'or cla.stdcode like '3%'or cla.stdcode like '4%'or cla.stdcode like '5%' or cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%'or cla.stdcode like '604%' then card.leijzj else 0 end) as i6,                            \n");
		sb.append("          sum(case when cla.stdcode like '101%'or cla.stdcode like '102%' or cla.stdcode like '103%' then card.leijzj else 0 end) as i7,                                                                                                                                                                               \n");
		sb.append("          sum(case when cla.stdcode like '2%' then card.leijzj else 0 end) as i8,                                                                                                                                                                                                                                      \n");
		sb.append("          sum(case when cla.stdcode like '3%' then card.leijzj else 0 end) as i9,                                                                                                                                                                                                                                      \n");
		sb.append("          sum(case when cla.stdcode like '4%' then card.leijzj else 0 end) as i10,                                                                                                                                                                                                                                     \n");
		sb.append("          sum(case when cla.stdcode like '5%' then card.leijzj else 0 end) as i11,                                                                                                                                                                                                                                     \n");
		sb.append("          sum(case when cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%'  then card.leijzj else 0 end) as i12,                                                                                                                                                  \n");
		sb.append("          sum(case when cla.stdcode like '605%' then card.leijzj else 0 end) as i13,                                                                                                                                                                                                                                   \n");
		sb.append("          sum(case when cla.stdcode like '1%'or cla.stdcode like '2%'or cla.stdcode like '3%'or cla.stdcode like '4%'or cla.stdcode like '5%' or cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%'or cla.stdcode like '604%'or cla.stdcode like '605%' then card.jingz else 0 end) as j5,   \n");
		sb.append("          sum(case when cla.stdcode like '1%'or cla.stdcode like '2%'or cla.stdcode like '3%'or cla.stdcode like '4%'or cla.stdcode like '5%' or cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%'or cla.stdcode like '604%' then card.jingz else 0 end) as j6,                             \n");
		sb.append("          sum(case when cla.stdcode like '101%'or cla.stdcode like '102%' or cla.stdcode like '103%' then card.jingz else 0 end) as j7,                                                                                                                                                                                \n");
		sb.append("          sum(case when cla.stdcode like '2%' then card.jingz else 0 end) as j8,                                                                                                                                                                                                                                       \n");
		sb.append("          sum(case when cla.stdcode like '3%' then card.jingz else 0 end) as j9,                                                                                                                                                                                                                                       \n");
		sb.append("          sum(case when cla.stdcode like '4%' then card.jingz else 0 end) as j10,                                                                                                                                                                                                                                      \n");
		sb.append("          sum(case when cla.stdcode like '5%' then card.jingz else 0 end) as j11,                                                                                                                                                                                                                                      \n");
		sb.append("          sum(case when cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%'  then card.jingz else 0 end) as j12,                                                                                                                                                   \n");
		sb.append("          sum(case when cla.stdcode like '605%' then card.jingz else 0 end) as j13,                                                                                                                                                                                                                                    \n");
		sb.append("          sum(case when cla.stdcode like '2%'and syzk.stdcode = '01' then card.shul else 0 end) as k8,                                                                                                                                                                                                                 \n");
		sb.append("          sum(case when cla.stdcode like '3%'and syzk.stdcode = '01' then card.shul else 0 end) as k9,                                                                                                                                                                                               \n");
		sb.append("          sum(case when cla.stdcode like '4%'and syzk.stdcode = '01' then card.shul else 0 end) as k10,                                                                                                                                                                                              \n");
		sb.append("          sum(case when cla.stdcode like '5%'and syzk.stdcode = '01' then card.shul else 0 end) as k11,                                                                                                                                                                                              \n");
		sb.append("          sum(case when (cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '01' then card.shul else 0 end) as k12,                                                                                                         \n");
		sb.append("          sum(case when cla.stdcode like '101%'or cla.stdcode like '102%' then card.zyjz else case when cla.stdcode like '103%'and syzk.stdcode = '01'  then card.jiaz else 0 end end) +                                                                                                          \n");
		sb.append("          sum(case when (cla.stdcode like '2%'or cla.stdcode like '3%'or cla.stdcode like '4%'or cla.stdcode like '5%'or cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '01'  then card.jiaz else 0 end) +           \n");
		sb.append("          sum(case when cla.stdcode like '6050411%' then card.zyjz else case when cla.stdcode like '605%' and syzk.stdcode = '01' then card.jiaz else  0 end end) as l5,                                                                                                                             \n");
		sb.append("          sum(case when cla.stdcode like '101%'or cla.stdcode like '102%' then card.zyjz else case when cla.stdcode like '103%'and syzk.stdcode = '01'  then card.jiaz else 0 end end) +                                                                                                          \n");
		sb.append("          sum(case when (cla.stdcode like '2%'or cla.stdcode like '3%'or cla.stdcode like '4%'or cla.stdcode like '5%'or cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '01'  then card.jiaz else 0 end) as l6,         \n");
		sb.append("          sum(case when cla.stdcode like '101%'or cla.stdcode like '102%' then card.zyjz else case when cla.stdcode like '103%'and syzk.stdcode = '01'  then card.jiaz else 0 end end) as l7,                                                                                                        \n");
		sb.append("          sum(case when cla.stdcode like '2%'and syzk.stdcode = '01' then card.jiaz else 0 end) as l8,                                                                                                                                                                                               \n");
		sb.append("          sum(case when cla.stdcode like '3%'and syzk.stdcode = '01' then card.jiaz else 0 end) as l9,                                                                                                                                                                                               \n");
		sb.append("          sum(case when cla.stdcode like '4%'and syzk.stdcode = '01' then card.jiaz else 0 end) as l10,                                                                                                                                                                                              \n");
		sb.append("          sum(case when cla.stdcode like '5%'and syzk.stdcode = '01' then card.jiaz else 0 end) as l11,                                                                                                                                                                                              \n");
		sb.append("          sum(case when (cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '01'  then card.jiaz else 0 end) as l12,                                                                                                        \n");
		sb.append("          sum(case when cla.stdcode like '6050411%' then card.zyjz else case when cla.stdcode like '605%' and syzk.stdcode = '01' then card.jiaz else  0 end end) as l13,                                                                                                                            \n");
		sb.append("          sum(case when cla.stdcode like '2%'and syzk.stdcode = '01' then card.leijzj else 0 end) as m8,                                                                                                                                                                                             \n");
		sb.append("          sum(case when cla.stdcode like '3%'and syzk.stdcode = '01' then card.leijzj else 0 end) as m9,                                                                                                                                                                                             \n");
		sb.append("          sum(case when cla.stdcode like '4%'and syzk.stdcode = '01' then card.leijzj else 0 end) as m10,                                                                                                                                                                                            \n");
		sb.append("          sum(case when cla.stdcode like '5%'and syzk.stdcode = '01' then card.leijzj else 0 end) as m11,                                                                                                                                                                                            \n");
		sb.append("          sum(case when (cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '01' then card.leijzj else 0 end) as m12,                                                                                                       \n");
		sb.append("          sum(case when cla.stdcode like '2%'and syzk.stdcode = '01' then card.jingz else 0 end) as n8,                                                                                                                                                                                              \n");
		sb.append("          sum(case when cla.stdcode like '3%'and syzk.stdcode = '01' then card.jingz else 0 end) as n9,                                                                                                                                                                                              \n");
		sb.append("          sum(case when cla.stdcode like '4%'and syzk.stdcode = '01' then card.jingz else 0 end) as n10,                                                                                                                                                                                             \n");
		sb.append("          sum(case when cla.stdcode like '5%'and syzk.stdcode = '01' then card.jingz else 0 end) as n11,                                                                                                                                                                                             \n");
		sb.append("          sum(case when (cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '01' then card.jingz else 0 end) as n12,                                                                                                        \n");
		sb.append("          sum(case when cla.stdcode like '2%'and syzk.stdcode = '02' then card.shul else 0 end) as o8,                                                                                                                                                                                               \n");
		sb.append("          sum(case when cla.stdcode like '3%'and syzk.stdcode = '02' then card.shul else 0 end) as o9,                                                                                                                                                                                               \n");
		sb.append("          sum(case when cla.stdcode like '4%'and syzk.stdcode = '02' then card.shul else 0 end) as o10,                                                                                                                                                                                              \n");
		sb.append("          sum(case when cla.stdcode like '5%'and syzk.stdcode = '02' then card.shul else 0 end) as o11,                                                                                                                                                                                              \n");
		sb.append("          sum(case when (cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '02' then card.shul else 0 end) as o12,                                                                                                         \n");
		sb.append("          sum(case when cla.stdcode like '101%'or cla.stdcode like '102%' then card.czjjz else case when cla.stdcode like '103%'and syzk.stdcode = '02'  then card.jiaz else 0 end end) +                                                                                                         \n");
		sb.append("          sum(case when (cla.stdcode like '2%'or cla.stdcode like '3%'or cla.stdcode like '4%'or cla.stdcode like '5%'or cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '02'  then card.jiaz else 0 end) +           \n");
		sb.append("          sum(case when cla.stdcode like '6050411%' then card.czjjz else case when cla.stdcode like '605%' and syzk.stdcode = '02' then card.jiaz else  0 end end) as p5,                                                                                                                            \n");
		sb.append("          sum(case when cla.stdcode like '101%'or cla.stdcode like '102%' then card.czjjz else case when cla.stdcode like '103%'and syzk.stdcode = '02'  then card.jiaz else 0 end end) +                                                                                                         \n");
		sb.append("          sum(case when (cla.stdcode like '2%'or cla.stdcode like '3%'or cla.stdcode like '4%'or cla.stdcode like '5%'or cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '02'  then card.jiaz else 0 end) as p6,         \n");
		sb.append("          sum(case when cla.stdcode like '101%'or cla.stdcode like '102%' then card.czjjz else case when cla.stdcode like '103%'and syzk.stdcode = '02'  then card.jiaz else 0 end end) as p7,                                                                                                       \n");
		sb.append("          sum(case when cla.stdcode like '2%'and syzk.stdcode = '02' then card.jiaz else 0 end) as p8,                                                                                                                                                                                               \n");
		sb.append("          sum(case when cla.stdcode like '3%'and syzk.stdcode = '02' then card.jiaz else 0 end) as p9,                                                                                                                                                                                               \n");
		sb.append("          sum(case when cla.stdcode like '4%'and syzk.stdcode = '02' then card.jiaz else 0 end) as p10,                                                                                                                                                                                              \n");
		sb.append("          sum(case when cla.stdcode like '5%'and syzk.stdcode = '02' then card.jiaz else 0 end) as p11,                                                                                                                                                                                              \n");
		sb.append("          sum(case when (cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '02'  then card.jiaz else 0 end) as p12,                                                                                                        \n");
		sb.append("          sum(case when cla.stdcode like '6050411%' then card.czjjz else case when cla.stdcode like '605%' and syzk.stdcode = '02' then card.jiaz else  0 end end) as p13,                                                                                                                           \n");
		sb.append("          sum(case when cla.stdcode like '2%'and syzk.stdcode = '02' then card.leijzj else 0 end) as q8,                                                                                                                                                                                             \n");
		sb.append("          sum(case when cla.stdcode like '3%'and syzk.stdcode = '02' then card.leijzj else 0 end) as q9,                                                                                                                                                                                             \n");
		sb.append("          sum(case when cla.stdcode like '4%'and syzk.stdcode = '02' then card.leijzj else 0 end) as q10,                                                                                                                                                                                            \n");
		sb.append("          sum(case when cla.stdcode like '5%'and syzk.stdcode = '02' then card.leijzj else 0 end) as q11,                                                                                                                                                                                            \n");
		sb.append("          sum(case when (cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '02' then card.leijzj else 0 end) as q12,                                                                                                       \n");
		sb.append("          sum(case when cla.stdcode like '2%'and syzk.stdcode = '02' then card.jingz else 0 end) as r8,                                                                                                                                                                                              \n");
		sb.append("          sum(case when cla.stdcode like '3%'and syzk.stdcode = '02' then card.jingz else 0 end) as r9,                                                                                                                                                                                              \n");
		sb.append("          sum(case when cla.stdcode like '4%'and syzk.stdcode = '02' then card.jingz else 0 end) as r10,                                                                                                                                                                                             \n");
		sb.append("          sum(case when cla.stdcode like '5%'and syzk.stdcode = '02' then card.jingz else 0 end) as r11,                                                                                                                                                                                             \n");
		sb.append("          sum(case when (cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '02' then card.jingz else 0 end) as r12,                                                                                                        \n");
		sb.append("          sum(case when cla.stdcode like '2%'and syzk.stdcode = '03' then card.shul else 0 end) as s8,                                                                                                                                                                                               \n");
		sb.append("          sum(case when cla.stdcode like '3%'and syzk.stdcode = '03' then card.shul else 0 end) as s9,                                                                                                                                                                                               \n");
		sb.append("          sum(case when cla.stdcode like '4%'and syzk.stdcode = '03' then card.shul else 0 end) as s10,                                                                                                                                                                                              \n");
		sb.append("          sum(case when cla.stdcode like '5%'and syzk.stdcode = '03' then card.shul else 0 end) as s11,                                                                                                                                                                                              \n");
		sb.append("          sum(case when (cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '03' then card.shul else 0 end) as s12,                                                                                                         \n");
		sb.append("          sum(case when cla.stdcode like '101%'or cla.stdcode like '102%' then card.xzjz else case when cla.stdcode like '103%'and syzk.stdcode = '03'  then card.jiaz else 0 end end) +                                                                                                          \n");
		sb.append("          sum(case when (cla.stdcode like '2%'or cla.stdcode like '3%'or cla.stdcode like '4%'or cla.stdcode like '5%'or cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '03'  then card.jiaz else 0 end) +           \n");
		sb.append("          sum(case when cla.stdcode like '6050411%' then card.xzjz else case when cla.stdcode like '605%' and syzk.stdcode = '03' then card.jiaz else  0 end end) as t5,                                                                                                                             \n");
		sb.append("          sum(case when cla.stdcode like '101%'or cla.stdcode like '102%' then card.xzjz else case when cla.stdcode like '103%'and syzk.stdcode = '03'  then card.jiaz else 0 end end) +                                                                                                          \n");
		sb.append("          sum(case when (cla.stdcode like '2%'or cla.stdcode like '3%'or cla.stdcode like '4%'or cla.stdcode like '5%'or cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '03'  then card.jiaz else 0 end) as t6,         \n");
		sb.append("          sum(case when cla.stdcode like '101%'or cla.stdcode like '102%' then card.xzjz else case when cla.stdcode like '103%'and syzk.stdcode = '03'  then card.jiaz else 0 end end) as t7,                                                                                                        \n");
		sb.append("          sum(case when cla.stdcode like '2%'and syzk.stdcode = '03' then card.jiaz else 0 end) as t8,                                                                                                                                                                                               \n");
		sb.append("          sum(case when cla.stdcode like '3%'and syzk.stdcode = '03' then card.jiaz else 0 end) as t9,                                                                                                                                                                                               \n");
		sb.append("          sum(case when cla.stdcode like '4%'and syzk.stdcode = '03' then card.jiaz else 0 end) as t10,                                                                                                                                                                                              \n");
		sb.append("          sum(case when cla.stdcode like '5%'and syzk.stdcode = '03' then card.jiaz else 0 end) as t11,                                                                                                                                                                                              \n");
		sb.append("          sum(case when (cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '03'  then card.jiaz else 0 end) as t12,                                                                                                        \n");
		sb.append("          sum(case when cla.stdcode like '6050411%' then card.xzjz else case when cla.stdcode like '605%' and syzk.stdcode = '03' then card.jiaz else  0 end end) as t13,                                                                                                                            \n");
		sb.append("          sum(case when cla.stdcode like '2%'and syzk.stdcode = '03' then card.leijzj else 0 end) as u8,                                                                                                                                                                                             \n");
		sb.append("          sum(case when cla.stdcode like '3%'and syzk.stdcode = '03' then card.leijzj else 0 end) as u9,                                                                                                                                                                                             \n");
		sb.append("          sum(case when cla.stdcode like '4%'and syzk.stdcode = '03' then card.leijzj else 0 end) as u10,                                                                                                                                                                                            \n");
		sb.append("          sum(case when cla.stdcode like '5%'and syzk.stdcode = '03' then card.leijzj else 0 end) as u11,                                                                                                                                                                                            \n");
		sb.append("          sum(case when (cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '03' then card.leijzj else 0 end) as u12,                                                                                                       \n");
		sb.append("          sum(case when cla.stdcode like '2%'and syzk.stdcode = '03' then card.jingz else 0 end) as v8,                                                                                                                                                                                              \n");
		sb.append("          sum(case when cla.stdcode like '3%'and syzk.stdcode = '03' then card.jingz else 0 end) as v9,                                                                                                                                                                                              \n");
		sb.append("          sum(case when cla.stdcode like '4%'and syzk.stdcode = '03' then card.jingz else 0 end) as v10,                                                                                                                                                                                             \n");
		sb.append("          sum(case when cla.stdcode like '5%'and syzk.stdcode = '03' then card.jingz else 0 end) as v11,                                                                                                                                                                                             \n");
		sb.append("          sum(case when (cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '03' then card.jingz else 0 end) as v12,                                                                                                        \n");
		sb.append("          sum(case when cla.stdcode like '2%'and syzk.stdcode = '04' then card.shul else 0 end) as w8,                                                                                                                                                                                               \n");
		sb.append("          sum(case when cla.stdcode like '3%'and syzk.stdcode = '04' then card.shul else 0 end) as w9,                                                                                                                                                                                               \n");
		sb.append("          sum(case when cla.stdcode like '4%'and syzk.stdcode = '04' then card.shul else 0 end) as w10,                                                                                                                                                                                              \n");
		sb.append("          sum(case when cla.stdcode like '5%'and syzk.stdcode = '04' then card.shul else 0 end) as w11,                                                                                                                                                                                              \n");
		sb.append("          sum(case when (cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '04' then card.shul else 0 end) as w12,                                                                                                         \n");
		sb.append("          sum(case when cla.stdcode like '101%'or cla.stdcode like '102%' then card.dczjz else case when cla.stdcode like '103%'and syzk.stdcode = '04'  then card.jiaz else 0 end end) +                                                                                                         \n");
		sb.append("          sum(case when (cla.stdcode like '2%'or cla.stdcode like '3%'or cla.stdcode like '4%'or cla.stdcode like '5%'or cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '04'  then card.jiaz else 0 end) +           \n");
		sb.append("          sum(case when cla.stdcode like '6050411%' then card.dczjz else case when cla.stdcode like '605%' and syzk.stdcode = '04' then card.jiaz else  0 end end) as x5,                                                                                                                            \n");
		sb.append("          sum(case when cla.stdcode like '101%'or cla.stdcode like '102%' then card.dczjz else case when cla.stdcode like '103%'and syzk.stdcode = '04'  then card.jiaz else 0 end end) +                                                                                                         \n");
		sb.append("          sum(case when (cla.stdcode like '2%'or cla.stdcode like '3%'or cla.stdcode like '4%'or cla.stdcode like '5%'or cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '04'  then card.jiaz else 0 end) as x6,         \n");
		sb.append("          sum(case when cla.stdcode like '101%'or cla.stdcode like '102%' then card.dczjz else case when cla.stdcode like '103%'and syzk.stdcode = '04'  then card.jiaz else 0 end end) as x7,                                                                                                       \n");
		sb.append("          sum(case when cla.stdcode like '2%'and syzk.stdcode = '04' then card.jiaz else 0 end) as x8,                                                                                                                                                                                               \n");
		sb.append("          sum(case when cla.stdcode like '3%'and syzk.stdcode = '04' then card.jiaz else 0 end) as x9,                                                                                                                                                                                               \n");
		sb.append("          sum(case when cla.stdcode like '4%'and syzk.stdcode = '04' then card.jiaz else 0 end) as x10,                                                                                                                                                                                              \n");
		sb.append("          sum(case when cla.stdcode like '5%'and syzk.stdcode = '04' then card.jiaz else 0 end) as x11,                                                                                                                                                                                              \n");
		sb.append("          sum(case when (cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '04'  then card.jiaz else 0 end) as x12,                                                                                                        \n");
		sb.append("          sum(case when cla.stdcode like '6050411%' then card.dczjz else case when cla.stdcode like '605%' and syzk.stdcode = '04' then card.jiaz else  0 end end) as x13,                                                                                                                           \n");
		sb.append("          sum(case when cla.stdcode like '2%'and syzk.stdcode = '04' then card.leijzj else 0 end) as y8,                                                                                                                                                                                             \n");
		sb.append("          sum(case when cla.stdcode like '3%'and syzk.stdcode = '04' then card.leijzj else 0 end) as y9,                                                                                                                                                                                             \n");
		sb.append("          sum(case when cla.stdcode like '4%'and syzk.stdcode = '04' then card.leijzj else 0 end) as y10,                                                                                                                                                                                            \n");
		sb.append("          sum(case when cla.stdcode like '5%'and syzk.stdcode = '04' then card.leijzj else 0 end) as y11,                                                                                                                                                                                            \n");
		sb.append("          sum(case when (cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '04' then card.leijzj else 0 end) as y12,                                                                                                       \n");
		sb.append("          sum(case when cla.stdcode like '2%'and syzk.stdcode = '04' then card.jingz else 0 end) as z8,                                                                                                                                                                                              \n");
		sb.append("          sum(case when cla.stdcode like '3%'and syzk.stdcode = '04' then card.jingz else 0 end) as z9,                                                                                                                                                                                              \n");
		sb.append("          sum(case when cla.stdcode like '4%'and syzk.stdcode = '04' then card.jingz else 0 end) as z10,                                                                                                                                                                                             \n");
		sb.append("          sum(case when cla.stdcode like '5%'and syzk.stdcode = '04' then card.jingz else 0 end) as z11,                                                                                                                                                                                             \n");
		sb.append("          sum(case when (cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%') and syzk.stdcode = '04' then card.jingz else 0 end) as z12                                                                                                         \n");
		sb.append("     from gams_assetcard as card                                                                                                                                                                                                                                                                     \n");
		sb.append("      left join gams_jc_assetclass as cla on card.zifl = cla.recid                                                                                                                                                                                                                                   \n");
		sb.append("      left join gams_jc_syzk as syzk  on card.syzk = syzk.recid  ,md_org as org ,                                                                                                                                                                                                                        \n");
		sb.append("          (select c.objectid, max(c.jizrq) as jizrq                                                                                                                                                                                                                                                  \n");
		sb.append("             from gams_assetcard as c                                                                                                                                                                                                                                                                \n");
		sb.append("            where to_char(c.jizrq, 'yyyy-MM-dd') <= '2019-12-31'                                                                                                                                                                                                                                  \n");
		sb.append("            group by c.objectid) as lasec                                                                                                                                                                                                                                                            \n");
		sb.append("    where lasec.objectid = card.objectid                                                                                                                                                                                                                                                          \n");
		sb.append("      and lasec.jizrq = card.jizrq                                                                                                                                                                                                                                                                \n");
		sb.append("      and card.cardstate in ('00','02')                                                                                                                                                                                                                                                         \n");
		sb.append("      and card.orgunit = org.recid                                                                                                                                                                                                                                                                \n");
		sb.append("      and org.stdcode = '000223'                                                                                                                                                                                                                                                                  \n");

		sb.append("  end ");
		RecordSet rs = null;
		DBCommand dbc = null;
		try {
			dbc = conn.prepareStatement(sb.toString());
			dbc.setArgumentValues(acctyear);
			rs = dbc.executeQuery();
			while (rs.next()) {
				for (RecordSetField hangSet : rs.getFields()) {
					//System.out.println(hangSet.getName()+"----------"+hangSet.getDouble());
					mapSR.put(hangSet.getName(), hangSet.getDouble());
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
			System.out.println("sql编译失败，请检查sql后再操作。");
		}finally{
			//释放资源
			if(null != dbc){
				dbc.unuse();
			}
		}
		return mapSR;
	}
	
	

	/**
	 * 2、期初账面数取数逻辑解析（取数逻辑中单位条件固定为：“000223单位”）：
	 * @param conn
	 * @param acctyear
	 * @return
	 */
	public static Map<String,Double> getGdzc_wxzc_qc(Context conn,int acctyear){
		Map<String,Double> mapSR = new LinkedHashMap<String,Double>();
		StringBuffer sb = new StringBuffer();
		sb.append("  define query getGdzc_wxzc_qc(@acctyear int) begin  ");
		sb.append("   select sum(case when cla.stdcode like '2%' then card.shul else 0 end) as c8,                                                                                                                                                                                                                                             ");
		sb.append("          sum(case when cla.stdcode like '3%' then card.shul else 0 end) as c9,                                                                                                                                                                                                                                             ");
		sb.append("          sum(case when cla.stdcode like '4%' then card.shul else 0 end) as c10,                                                                                                                                                                                                                                            ");
		sb.append("          sum(case when cla.stdcode like '5%' then card.shul else 0 end) as c11,                                                                                                                                                                                                                                            ");
		sb.append("          sum(case when cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%' then card.shul else 0 end) as c12,                                                                                                                                                          ");
		sb.append("          sum(case when cla.stdcode like '1%'or cla.stdcode like '2%'or cla.stdcode like '3%'or cla.stdcode like '4%'or cla.stdcode like '5%' or cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%'or cla.stdcode like '604%'or cla.stdcode like '605%' then card.jiaz else 0 end) as d5,         ");
		sb.append("          sum(case when cla.stdcode like '1%'or cla.stdcode like '2%'or cla.stdcode like '3%'or cla.stdcode like '4%'or cla.stdcode like '5%' or cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%'or cla.stdcode like '604%' then card.jiaz else 0 end) as d6,                                   ");
		sb.append("          sum(case when cla.stdcode like '101%'or cla.stdcode like '102%' or cla.stdcode like '103%' then card.jiaz else 0 end)  as d7,                                                                                                                                                                                      ");
		sb.append("          sum(case when cla.stdcode like '2%' then card.jiaz else 0 end)  as d8,                                                                                                                                                                                                                                             ");
		sb.append("          sum(case when cla.stdcode like '3%' then card.jiaz else 0 end)  as d9,                                                                                                                                                                                                                                             ");
		sb.append("          sum(case when cla.stdcode like '4%' then card.jiaz else 0 end) as d10,                                                                                                                                                                                                                                            ");
		sb.append("          sum(case when cla.stdcode like '5%' then card.jiaz else 0 end) as d11,                                                                                                                                                                                                                                            ");
		sb.append("          sum(case when cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%'  then card.jiaz else 0 end) as d12,                                                                                                                                                         ");
		sb.append("          sum(case when cla.stdcode like '605%' then card.jiaz else 0 end) as d13,                                                                                                                                                                                                                                          ");
		sb.append("          sum(case when cla.stdcode like '1%'or cla.stdcode like '2%'or cla.stdcode like '3%'or cla.stdcode like '4%'or cla.stdcode like '5%' or cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%'or cla.stdcode like '604%'or cla.stdcode like '605%' then card.leijzj else 0 end) as e5,       ");
		sb.append("          sum(case when cla.stdcode like '1%'or cla.stdcode like '2%'or cla.stdcode like '3%'or cla.stdcode like '4%'or cla.stdcode like '5%' or cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%'or cla.stdcode like '604%' then card.leijzj else 0 end) as e6,                                 ");
		sb.append("          sum(case when cla.stdcode like '101%'or cla.stdcode like '102%' or cla.stdcode like '103%' then card.leijzj else 0 end) as e7,                                                                                                                                                                                    ");
		sb.append("          sum(case when cla.stdcode like '2%' then card.leijzj else 0 end) as e8,                                                                                                                                                                                                                                           ");
		sb.append("          sum(case when cla.stdcode like '3%' then card.leijzj else 0 end) as e9,                                                                                                                                                                                                                                           ");
		sb.append("          sum(case when cla.stdcode like '4%' then card.leijzj else 0 end) as e10,                                                                                                                                                                                                                                          ");
		sb.append("          sum(case when cla.stdcode like '5%' then card.leijzj else 0 end) as e11,                                                                                                                                                                                                                                          ");
		sb.append("          sum(case when cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%'  then card.leijzj else 0 end) as e12,                                                                                                                                                       ");
		sb.append("          sum(case when cla.stdcode like '605%' then card.leijzj else 0 end) as e13,                                                                                                                                                                                                                                        ");
		sb.append("          sum(case when cla.stdcode like '1%'or cla.stdcode like '2%'or cla.stdcode like '3%'or cla.stdcode like '4%'or cla.stdcode like '5%' or cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%'or cla.stdcode like '604%'or cla.stdcode like '605%' then card.jingz else 0 end) as f5,        ");
		sb.append("          sum(case when cla.stdcode like '1%'or cla.stdcode like '2%'or cla.stdcode like '3%'or cla.stdcode like '4%'or cla.stdcode like '5%' or cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%'or cla.stdcode like '604%' then card.jingz else 0 end) as f6,                                  ");
		sb.append("          sum(case when cla.stdcode like '101%'or cla.stdcode like '102%' or cla.stdcode like '103%' then card.jingz else 0 end) as f7,                                                                                                                                                                                     ");
		sb.append("          sum(case when cla.stdcode like '2%' then card.jingz else 0 end) as f8,                                                                                                                                                                                                                                            ");
		sb.append("          sum(case when cla.stdcode like '3%' then card.jingz else 0 end) as f9,                                                                                                                                                                                                                                            ");
		sb.append("          sum(case when cla.stdcode like '4%' then card.jingz else 0 end) as f10,                                                                                                                                                                                                                                           ");
		sb.append("          sum(case when cla.stdcode like '5%' then card.jingz else 0 end) as f11,                                                                                                                                                                                                                                           ");
		sb.append("          sum(case when cla.stdcode like '601%'or cla.stdcode like '602%' or cla.stdcode like '603%' or cla.stdcode like '604%'  then card.jingz else 0 end) as f12,                                                                                                                                                        ");
		sb.append("          sum(case when cla.stdcode like '605%' then card.jingz else 0 end) as f13                                                                                                                                                                                                                                          ");
		sb.append("     from gams_assetcard as card                                                                                                                                                                                                                                                                                            ");
		sb.append("      left join gams_jc_assetclass as cla on card.zifl = cla.recid ,md_org as org ,                                                                                                                                                                                                                                            ");
		sb.append("          (select c.objectid, max(c.jizrq) as jizrq                                                                                                                                                                                                                                                                         ");
		sb.append("             from gams_assetcard as c                                                                                                                                                                                                                                                                                       ");
		sb.append("            where to_char(c.jizrq, 'yyyy-MM-dd') <= '2018-12-31'                                                                                                                                                                                                                                                        ");
		sb.append("            group by c.objectid) as lasec                                                                                                                                                                                                                                                                                   ");
		sb.append("    where lasec.objectid = card.objectid                                                                                                                                                                                                                                                                                 ");
		sb.append("      and lasec.jizrq = card.jizrq                                                                                                                                                                                                                                                                                       ");
		sb.append("      and card.cardstate in ('00','02')                                                                                                                                                                                                                                                                                ");
		sb.append("      and card.orgunit = org.recid                                                                                                                                                                                                                                                                                       ");
		sb.append("      and org.stdcode = '000223'                                                                                                                                                                                                                                                                                         ");
		sb.append("  end ");
		RecordSet rs = null;
		DBCommand dbc = null;
		try {
			dbc = conn.prepareStatement(sb.toString());
			dbc.setArgumentValues(acctyear);
			rs = dbc.executeQuery();
			while (rs.next()) {
				for (RecordSetField hangSet : rs.getFields()) {
					mapSR.put(hangSet.getName(), hangSet.getDouble());
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
			System.out.println("sql编译失败，请检查sql后再操作。");
		}finally{
			//释放资源
			if(null != dbc){
				dbc.unuse();
			}
		}
		return mapSR;
	}

}
